export default projects = [
  {
    type: 'frontend',
    imgUrl: '/twilioMeet.jpg',
    title: 'Google Meet Clone',
    description: 'Google meet clone for midudev\'s hackathon, built in React, using twilio API',
    repository: 'https://github.com/camilonore/twilio-hackathon',
    website: 'https://twilio-hackathon-alpha.vercel.app/',
  },
  {
    type: 'frontend',
    imgUrl: '/tmyp.jpg',
    title: 'Tell Me Your Problem',
    description: 'Application in which posts can be created to search for a developer who can solve your problem, made with Nextjs, NextAuth, MongoDB and CSS',
    repository: 'https://github.com/camilonore/tell-me-your-problem',
    website: '',
  },
  {
    type: 'frontend',
    imgUrl: '/nextCalendar.jpg',
    title: 'Next Calendar',
    description: 'Calendar made in NextJs, MongoDb, and pure CSS',
    repository: 'https://github.com/camilonore/next-calendar',
    website: '',
  },
  {
    type: 'frontend',
    imgUrl: '/rickAndMorty.jpg',
    title: 'Rick and Morty',
    description: 'Rick and Morty website using React, and consuming the API',
    repository: 'https://github.com/camilonore/rick-and-morty-api',
    website: 'https://rick-and-morty-api-mu.vercel.app/',
  },
  {
    type: 'frontend',
    imgUrl: '/calculator.jpg',
    title: 'Calculator',
    description: 'Basic calculator made in React with Vite',
    repository: 'https://github.com/camilonore/ReactCalcutator',
    website: 'https://react-calcutator.vercel.app/',
  },
  {
    type: 'frontend',
    imgUrl: '/reactIot.jpg',
    title: 'React IOT',
    description:
      'Basic iot project made in React, communication betwen the website and an ESP8266 programmed in arduino, for the communication between website and ESP I used firebase',
    repository: 'https://github.com/camilonore/iot-basic-project',
    website: 'https://iot-basic-project.vercel.app/',
  },
  {
    type: 'backend',
    imgUrl: '/moviesApi.jpg',
    title: 'Movies Api',
    description: 'Restful Api made in Nodejs, Express, MongoDb and also TDD implemented',
    repository: 'https://github.com/camilonore/movies-api',
    website: '',
  },
];
